### ISSUE TITLE
how to setup pin LCD NT35510 LCD 480x800 in arduino mega 2560?

### ISSUE THREAD

**Issue by Alis-Dev-idn** [moononournation/Arduino_GFX#110] opened 2022-01-13 08:55 UTC
I'm confused about this library, which pins are used for the NT35510 LCD 480x800 on the Arduino Mega 2560?

**Comment by moononournation** [comment] 2022-01-13 13:52
As you can see at README Tobe Support Dev Board, this item is on the wish list.

**Comment by dapostol73** [comment] 2023-03-23 01:53
Any update on this, been trying to get this to work with my Arduino Mega 2560 with no success.  Even if you just paste the code for the example video on [YouTube](https://youtu.be/C_1ASzUN3bg), that would be great.

**Comment by moononournation** [comment] 2023-03-23 21:40
not yet have this databus

**Comment by moononournation** [comment] 2023-03-25 02:32
You are using 8-bit or 16-bit parallel interface?

**Comment by moononournation** [comment] 2023-03-25 13:05
Just added a Arduino_SWPAR16 databus class, you may get update to test it.

**Comment by dapostol73** [comment] 2023-03-25 16:29
Here is the board itself, it support both but mine comes from the factory with the 16 Bit Parallel resistor soldered, so I assume I require an Arduino_SWPAR16 databus.

http://www.lcdwiki.com/4.0inch_Arduino_Display-Mega2560_NT35510

**Comment by dapostol73** [comment] 2023-03-25 16:34
Happy to test too...if you need to see any of the hardware information, I've uploaded the custom LCDWIKI_KBV libraries here for the this NT35510 if that helps.

https://github.com/dapostol73/WeatherStationInternal/tree/main/lib/

**Comment by moononournation** [comment] 2023-03-26 00:44
I have not tested with the new class, can you help to test it?

**Comment by dapostol73** [comment] 2023-03-26 22:35
I did some testing yesterday, I got to work with following DataBus

Arduino_DataBus *bus = new Arduino_SWPAR16(38, 40, 39, 43,
37, 36, 35, 34, 33, 32, 31, 30,
22, 23, 24, 25, 26, 27, 28, 29);

I did find the clear was a bit slow, not sure if this is because this bus is Software versus using a hardware version for the Mega

**Comment by moononournation** [comment] 2023-03-26 23:04
Thx for your information. Seems this display aligned all pins well to port C and A, it is possible to make Arduino_AVRPAR16 databus for it.

**Comment by moononournation** [comment] 2023-03-27 11:23
Just create the Arduino_AVRPAR16 databus, please get update and test it:
```
Arduino_DataBus *bus = new Arduino_AVRPAR8(38 /* DC */, 40 /* CS */, 39 /* WR */, 43 /* RD */, 3 /* PORT LOW */, 1 /* PORT HIGH */);
```

**Comment by dapostol73** [comment] 2023-03-27 20:35
Getting this error when I try and use Arduino_AVRPAR16 directly.

Arduino_DataBus *bus = new Arduino_AVRPAR16(38, 40, 39, 43, 3 /* PORT LOW */, 1 /* PORT HIGH */);

`Linking .pio\build\megaatmega2560\firmware.elf
C:\Users\dapos\AppData\Local\Temp\ccXTsnAC.ltrans0.ltrans.o: In function `Arduino_AVRPAR16::writeC8D16D16(unsigned char, unsigned int, unsigned int)':
<artificial>:(.text+0x1ff4): undefined reference to `Arduino_AVRPAR16::WRITE16(unsigned int)'
<artificial>:(.text+0x200a): undefined reference to `Arduino_AVRPAR16::WRITE16(unsigned int)'
C:\Users\dapos\AppData\Local\Temp\ccXTsnAC.ltrans0.ltrans.o: In function `Arduino_AVRPAR16::writeC8D16(unsigned char, unsigned int)':<artificial>:(.text+0x203e): undefined reference to `Arduino_AVRPAR16::WRITE16(unsigned int)'
C:\Users\dapos\AppData\Local\Temp\ccXTsnAC.ltrans0.ltrans.o: In function `Arduino_AVRPAR16::writePixels(unsigned int*, unsigned long)':
<artificial>:(.text+0x2076): undefined reference to `Arduino_AVRPAR16::WRITE16(unsigned int)'
C:\Users\dapos\AppData\Local\Temp\ccXTsnAC.ltrans0.ltrans.o: In function `Arduino_AVRPAR16::write16(unsigned int)':
<artificial>:(.text+0x208e): undefined reference to `Arduino_AVRPAR16::WRITE16(unsigned int)'
C:\Users\dapos\AppData\Local\Temp\ccXTsnAC.ltrans0.ltrans.o:<artificial>:(.text+0x20a6): more undefined references to `Arduino_AVRPAR16::WRITE16(unsigned int)' follow
C:\Users\dapos\AppData\Local\Temp\ccXTsnAC.ltrans0.ltrans.o:(.rodata+0xa3): undefined reference to `Arduino_AVRPAR16::writeC8D16D16Split(unsigned char, unsigned int, unsigned int)'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\megaatmega2560\firmware.elf] Error 1`

**Comment by moononournation** [comment] 2023-03-27 23:02
fixed the error, please get update and try again:
```
Arduino_DataBus *bus = new Arduino_AVRPAR16(38 /* DC */, 40 /* CS */, 39 /* WR */, 43 /* RD */, 3 /* PORT LOW */, 1 /* PORT HIGH */);
```

**Comment by dapostol73** [comment] 2023-03-28 02:39
It compile now, but when I upload there is unfortunately no response of update on the screen, it just stays black.

`Arduino_DataBus *bus = new Arduino_AVRPAR16(38 /* DC */, 40 /* CS */, 39 /* WR */, 43 /* RD */, 3 /* PORT LOW */, 1 /* PORT HIGH */);
Arduino_GFX *gfx = new Arduino_NT35510(bus, 41, 0 /* rotation */);`

**Comment by moononournation** [comment] 2023-03-28 02:41
wild guess only, try alter port number to 1, 3

**Comment by dapostol73** [comment] 2023-03-28 02:43
No change

**Comment by moononournation** [comment] 2023-03-28 02:46
Ok, I will check the code tonight. And the SWPAR16 should be a little bit faster in latest version.

**Comment by dapostol73** [comment] 2023-03-28 02:48
Thanks, ya....I tried the SWPAR16 again to verify it was working, notice it was a lot faster.

**Comment by moononournation** [comment] 2023-03-28 13:47
Just checked the code and fixed somethings. I think it should work now.

**Comment by dapostol73** [comment] 2023-03-29 00:48
Success!!! I'll test now with my more complicated program 

![20230328_174730.jpg](https://user-images.githubusercontent.com/75643490/228398129-fed5f0db-e438-4e23-b71a-a32a2a92c46f.jpg)

**Comment by moononournation** [comment] 2023-03-29 00:52
Great! Can you help to prepare a PDQgraphicstest Youtube link? I will add it to the README.md. Thanks in advance.

**Comment by dapostol73** [comment] 2023-03-29 00:53
Sure what is required for that?

**Comment by moononournation** [comment] 2023-03-29 00:55
Just run the PDQgraphicstest.ino example in Arduino_GFX from start to end

**Comment by dapostol73** [comment] 2023-03-29 01:27
Looks like we have a problem, the test freezes here. Also the testPixel() is really slow VS other draws

![20230328_182539.jpg](https://user-images.githubusercontent.com/75643490/228402631-3bfa7c09-1dfc-40ad-8289-d60e62aaef74.jpg)

**Comment by dapostol73** [comment] 2023-03-29 01:45
My project is already read running, so I am good, I just replaced my wrapper on LCDWIKI lib that make the same calls.

**Comment by moononournation** [comment] 2023-03-29 11:23
Ok, then I close this request.

**Closed by moononournation** 2023-03-29 11:23 UTC

**Comment by dapostol73** [comment] 2023-03-29 16:07
Should I open another issue about the crash/freeze when running PDQgraphictest.ino then?

**Comment by moononournation** [comment] 2023-03-29 22:38
If you encounter similar issue in your project, you can raise it. I think it just because high resolution of PDQgraphicstest pushed to touch the MEGA 2560 resource limit, e.g. out of memory.

**Comment by dapostol73** [comment] 2023-03-30 00:08
Here is the video of the PDQ Graphics Test running, not sure you want this public yet....but allows you to see how slow it is when doing some of the tests.

https://www.youtube.com/watch?v=10VSWyrh2gw

**Comment by moononournation** [comment] 2023-03-30 00:17
Thx, yes this is pushing the limit of the MEGA 2560. But I think this is already better than SWPAR16 a lot.

**Comment by dapostol73** [comment] 2023-03-30 00:49
Not sure about that, I did two tests.

1. Removed the 2 arc test and it completed fine.
2. Ran each Arc test on its own and they both frooze.

Think it something to do with the arc function. In my app I have my own, which is why I'm not seeing the freeze

**Comment by moononournation** [comment] 2023-03-30 00:51
Arc tests are the only test using floating point. It may be the hint

**Comment by dapostol73** [comment] 2023-04-06 01:55
So I did some more digging into the Arc Test.  It seems that the issue start as soon as the Inner\Outer Radius of the arc gets over 180.  I did some serial prints and it is still running....but for some reason it doesn't draw anything an become super sluggish.

For example, the first line works, the second and third one are slow and draw nothing.
```
  gfx->fillArc(240, 400, 174, 177, 0, 150, RED);
  gfx->fillArc(240, 400, 180, 183, 0, 150, RED);
  gfx->fillArc(240, 400, 186, 189, 0, 150, RED);
```

**Comment by moononournation** [comment] 2023-04-06 02:15
Thx for your findings. Seem it caused by the different behavior of handling floating point in different platform. The arc function is come from other libraries, may be I should rewrite it use integer only just like circle functions.
